#!/bin/bash
# A simple wrapper to fixup path issues and start ft8goblin without installing...

# Set a reasonable default for even ten year old machines...
[ -z "${NPROC}" ] && NPROC=8

if [ ! -x bin/ft8goblin ]; then
   echo "Hang on, we need to compile things... This should only take a moment."
   make clean
   make -j${NPROC} world
fi

# Add ./lib to the library search path
export LD_LIBRARY_PATH=./lib:${LD_LIBRARY_PATH}

# Start ft8goblin
./bin/ft8goblin
